### ISSUE TITLE
inconsistent return types

### ISSUE THREAD

**Issue by jamestalmage** [yisibl/num2fraction#3]
```
if (num === 0) return 0
```
should return a string (`"0"`).

it seems wrong that it should return a number only in that special case

**Comment by yisibl** [comment]
Fix: https://github.com/yisibl/num2fraction/commit/25fb5d0665fe4eb41a316f83bd5f3e379e7ea0e3

**Comment by smonkey72** [comment]
Please remove `console.log(num2fraction('0'))` from https://github.com/yisibl/num2fraction/commit/25fb5d0665fe4eb41a316f83bd5f3e379e7ea0e3 again.

**Comment by dsine-de** [comment]
#4 should do that
